[project]
name = "yoloview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
keywords = ["ocr", "yolo", "ai", "vision"]
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "googletrans>=4.0.2",
    "image-quality>=1.2.7",
    "matplotlib>=3.10.3",
    "opencv-python==4.11.0.86",
    "paddleocr>=3.4.0",
    "paddlepaddle>=3.3.0",
    "paddlex[base]>=3.4.1",
    "pandas>=2.2.3",
    "pillow>=11.2.1",
    "pillow-heif>=0.22.0",
    "pycocotools>=2.0.8",
    "pyside6>=6.9.0",
    "pyside6-fluent-widgets[full]>=1.8.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "scikit-image>=0.25.2",
    "tqdm>=4.67.1",
    "ultralytics>=8.4.30",
    "huggingface-hub>=1.4.1",
    "transformers>=5.2.0",
]

[project.optional-dependencies]
cpu = [
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
    "torchvision==0.24.1",
]
cu128 = [
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
    "torchvision>=0.24.1",
]
glmocr = [
    "accelerate>=1.12.0",
    "flask>=3.1.3",
    "portalocker>=3.2.0",
    "python-dotenv>=1.2.1",
    "wordfreq>=3.1.1",
    "sentencepiece>=0.2.1",
    "pypdfium2>=5.5.0",
    "pytest>=9.0.2",
]
all = [
    "tokenizers>=0.22.2",
    "accelerate>=1.12.0",
    "flask>=3.1.3",
    "portalocker>=3.2.0",
    "python-dotenv>=1.2.1",
    "wordfreq>=3.1.1",
    "sentencepiece>=0.2.1",
    "pypdfium2>=5.5.0",
    "pytest>=9.0.2",
]

[tool.setuptools]
packages = []

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]
torchaudio = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
